# ansible-galaxy install geerlingguy.nginx
---
- hosts: ci
  become: yes
  roles:
    - role: geerlingguy.nginx
      nginx_remove_default_vhost: true
      nginx_vhosts:
       - listen: "80 default_server"
         server_name: "alpha.idamob.ru"
         extra_parameters: |
           location / {
             proxy_pass http://jenkins;
           }
      nginx_upstreams:
       - name: jenkins
         servers: { "localhost:8080" }
